site_name: Picovico - API 2.7 Documentation
heme: material
repo_url: https://github.com/picovico/apidocs
site_author: Picovico Inc.
docs_dir: docs
extra_css:
 - extras/screen.css
nav:
 - 'Home': 'index.md'
 - 'Login Flow': 'account/index.md'
 - 'API Application Callback': 'account/api_callback.md'
 - 'Endpoints' : 'videos/index.md'
 - 'Picovico System Provided Music' : 'musics/index.md'
 - 'Styles Details' : 'styles/index.md'
 - 'SDK / Libraries' : 'sdk/index.md'
