FORMAT: 1A
HOST: https://api.picovico.com/v2.1

# Picovico API
The Picovico API provides interface to access and integrate the video rendering functionality into your own platform. Our API is organized around REST, has resource-oriented URLs, and uses HTTP response codes to indicate errors. We support cross-origin resource sharing, allowing you to interact securely with our API from a client-side web application (though API Keys should never be exposed in any public website's client-side code). JSON is the standard for all API responses, including errors.


| **Platform version**  |      2.0      |
|--|--|
| **Authentication** | Basic Auth |
| **API Version** | 2.1 |
| **API Root** | https://api.picovico.com/v2.1/ |
| **SSL** | Yes |
| **Response Type** | JSON |


# Group Authentication
Picovico API follows a simple login flow. Each account is provided with `username` and `password` for authentication. Upon successful login, `access_key` and `access_token` are provided in the response.

*`X-Access-Key` and `X-Access-Token` headers are required for all authentication required requests.*

As of API Version 2.1, Login Flow has some modifications. Each login request must provide `app_id` as a mandatory third parameter. Also there are two different login scnenarios and respective endpoints.

# Login with username and password [/login]
This endpoint is useful in case if you want to login with your username and password.

## Login with password [POST]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + app_id: Picovico Provided Application ID (string, required)
        + username: Your Username (string, required)
        + password: Your Password (string, required)


+ Response 200 (application/json) 
        
        {
            "access_key": "a0sdfaosdfaksdflaksdfa0sdfasd",
            "access_token": "adsfa0sdfasdfasdfasdasdfadsfa",
            "id": "nX02dY"
        }

# Login with app_id and app_secret [/login/app]

Create an app from your developer dashboard. Use the app_id and app_secret for the app created.


## Login with app_secret [POST]

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + app_id: Picovico Provided Application ID (string, required)
        + app_secret: Picovico Provided Application Secret (string, required)

+ Response 200 (application/json) 
        
        {
            "access_key": "a0sdfaosdfaksdflaksdfa0sdfasd",
            "access_token": "adsfa0sdfasdfasdfasdasdfadsfa",
            "id": "nX02dY"
        }


# Group Styles

# Styles API [/styles]
To create a video, its mandatory to specify a style. When your video is generated, its rendered as per the style selected and content specified.

+ Model (application/json)

## List All Styles [GET]
Fetches the styles available in your account. If your account has some custom styles, you will receive those too.

+ Response 200 (application/json)
    
    + Attributes
        + name (string) - Name of the style
        + category (string) - One of the available style categories. eg. Premium, Stardard
        + is_featured (boolean) - True / False
        + machine_name (string) - Unique machine readable identifier
        + description (string) - Quick information about the style.
        + scope (string) - This style can be used in cases A, B, etc...
        + order (number) - Numeric value to indicate ordering if required
        + sample_url (string) - URL for the sample video
        + thumbnail (string) - URL for the style thumbnail
        + type (string) - type related to style such as "premium"
        + youtube_url (string) - URL id for youtube link if available
        + limits (object) - Style limitations for different quality levels, and others
            + quality (array) - Limits for the different quality levels
                + res (string) - One of the available resolutions (360, 480, 720)
                + white_labeled (boolean) - Whether white label feature is allowed or not.
                + coins (number) - Cost of rendering for the mentioned quality.
            + title_length - Maximum length for TITLE parameter in text slides
            + text_length - Maximum length for TEXT parameter in text slides
    
    + Body

        [
            {
                "category": "Premium",
                "is_featured": true,
                "name": "Vanilla",
                "machine_name": "vanilla",
                "description": "Simply Elegant",
                "scope": "Use in simple presentations, elegant slideshows & realestate.",
                "limits": {
                    "quality": [
                        {
                            "res": 360,
                            "white_labeled": false
                            "coins": 50
                        },
                        {
                            "res": 480,
                            "white_labeled": false
                            "coins": 100
                        },
                        {
                            "res": 720
                            "white_labeled": true
                            "coins": 150
                        }
                    ],
                    "title_length": 50,
                    "text_length": 100
                },
                "order": 1,
                "sample_url": "http://example.com/some-picovico-sample-video.mp4",
                "thumbnail": "http://example.com/some-picovico-sample-thumbnail.jpg"
                "type"" "premium",
                "youtube_url": "vRrSZZ2wwYA"
            },
            {
                "category": "Premium",
                "is_featured": true,
                "name": "Party",
                "machine_name": "party_default",
                "description": "Party description",
                "scope": "for parties",
                "limits": {
                    "quality": [
                        {
                            "res": 360,
                            "white_labeled": false
                            "coins": 50
                        },
                        {
                            "res": 480,
                            "white_labeled": false
                            "credits": 100
                        },
                        {
                            "res": 720
                            "white_labeled": false
                            "credits": 150
                        }
                    ],
                    "title_length": 50,
                    "text_length": 100
                },
                "order": 1,
                "sample_url": "http://example.com/some-picovico-sample-video.mp4",
                "thumbnail": "http://example.com/some-picovico-sample-thumbnail.jpg",
                "type"" "premium",
                "youtube_url": "vRrSZZ2wwYA"
            }
        ]


## Group Musics

Resources related to musics in the API. Musics include both system provided and uploaded musics.

# Musics API [/musics]

Inorder to append music to video, Picovico provides some music. You can upload your own music as well.

+ Model (application/json)

## List all system music [GET]

Fetches all musics provided by picovico.

+ Attributes
    + category (string) - Music Category e.g. Christmas,
    + is_featured (boolean) - Whether the music is featured or not.,
    + artist (string) - Artist of music [Unknown if not available],
    + title (string) - Title of music [Unknown if not available],
    + preview_url (string) - Preview URL of music,
    + duration (number) - Duration in seconds,
    + id (string) - Unique identifier to the music object.

+ Response 200 (application/json)
        
        [
            {
                "category": "Musical",
                "is_featured": false,
                "artist": "Kevin MacLeod",
                "title": "Waterford",
                "preview_url": "https://s3-us-west-2.amazonaws.com/pv-audio-library/free-music/preview/Musical/Waterford.mp3",
                "duration": 113,
                "id": "NhLIg"
            },
            {
                "category": "Musical",
                "is_featured": false,
                "artist": "Kevin MacLeod",
                "title": "Wexford",
                "preview_url": "https://s3-us-west-2.amazonaws.com/pv-audio-library/free-music/preview/Musical/Wexford.mp3",
                "duration": 117,
                "id": "NhLIe"
            }
        ]

# Personal Music API [/me/musics]

+ Model (application/json)

## List all user uploaded music [GET]

Fetches User uploaded music.

Attributes and response similar to system musics.


+ Response 200 (application/json)
    {
        musics: []
    }

